const RAW_MODES={
 monuments:['Taj Mahal|taj-mahal.jpg','Torre de Pisa|pisa.jpg','Torre Eiffel|torre-eiffel.jpg','Angkor Wat|angkor-wat.jpg','Plaça de Sant Pere|st-peter-s-square.jpg','Sagrada Família|sagrada-fam-lia.jpg','Big Ben|big-ben.jpg','Piràmides de Gizeh|great-pyramid-of-giza.jpg','Partenó|parthenon.jpg','Colosseu|colosseum.jpg','Stonehenge|stonehenge.jpg','Machu Picchu|machu-picchu.jpg','Muralla Xinesa|great-wall.jpg'],
 dishes:['Paella|paella.jpg','Sushi|sushi.jpg','Pizza|pizza.jpg','Tacos|tacos.jpg','Croissant|croissant.jpg','Ramen|ramen.jpg','Hamburguesa|burger.jpg'],
 objects:['Paraigua|paraigua.jpg','Tassa|tassa.jpg','Bicicleta|bicicleta.jpg','Tisores|tisores.jpg','Raspall de dents|raspall-dents.jpg','Motxilla|motxilla.jpg','Clau|clau.jpg','Paella de cuina|paella-cuina.jpg'],
 artworks:["La Gioconda|la-gioconda.jpg","La nit estrellada|nit-estrellada.jpg","El crit|el-crit.jpg","Guernica|guernica.jpg","El petó|el-peto.jpg","La persistència de la memòria|persistencia-memoria.jpg","Noia amb una arracada de perla|noia-perla.jpg","El naixement de Venus|naixement-venus.jpg"]
};
const MODE_INFO={monuments:['Monuments del món','🏛️','arquitectura, ciutat i país','forma, materials i entorn'],dishes:['Plats coneguts','🍽️','nom del plat, país i ingredients','colors, forma i presentació'],objects:['Objectes quotidians','🧺','nom de l’objecte i ús','forma, peces i material'],artworks:["Obres d'art famoses",'🖼️','títol, autor i moviment','composició, colors i figures']};
const CARD_DETAILS={
 'Taj Mahal':['Índia','Agra','mausoleu','marbre','Mughal'], 'Torre de Pisa':['Itàlia','inclinada','campanar','Toscana','Galileu'], 'Torre Eiffel':['París','França','ferro','Champ de Mars','torre'], 'Angkor Wat':['Cambodja','temple','Khmer','selva','jungle'], 'Plaça de Sant Pere':['Vaticà','Roma','Papa','Bernini','basílica'], 'Sagrada Família':['Gaudí','Barcelona','Catalunya','basílica','temple'], 'Big Ben':['Londres','Anglaterra','rellotge','Parlament','Tàmesi'], 'Piràmides de Gizeh':['Egipte','faraó','desert','esfinx','Kheops'], 'Partenó':['Atenes','Grècia','Acròpolis','temple','dòric'], 'Colosseu':['Roma','gladiador','amfiteatre','romà','Itàlia'], 'Stonehenge':['Anglaterra','pedres','megalític','druida','cercle'], 'Machu Picchu':['Perú','inca','Andes','Cuzco','muntanya'], 'Muralla Xinesa':['Xina','gran muralla','torres','Mongòlia','fortificació'],
 'Paella':['València','arròs','safrà','marisc','Espanya'], 'Sushi':['Japó','arròs','peix cru','nori','wasabi'], 'Pizza margarita':['Itàlia','tomàquet','mozzarella','formatge','massa'], 'Tacos':['Mèxic','truita','guacamole','picant','farcit'], 'Croissant':['França','pasta de full','mantega','esmorzar','mitja lluna'], 'Ramen':['Japó','sopa','fideus','brou','bol'], 'Hamburguesa':['pa','carn','formatge','fast food','burger'],
 'Paraigua':['pluja','aigua','cobrir','varetes','mànec'], 'Tassa':['cafè','te','beure','nansa','ceràmica'], 'Bicicleta':['rodes','pedalar','manillar','cadena','casc'], 'Tisores':['tallar','paper','fulles','anelles','costura'], 'Raspall de dents':['dents','pasta dental','higiene','boca'], 'Motxilla':['esquena','bossa','escola','corretges','cremallera'], 'Clau':['pany','porta','obrir','tancar','dents'], 'Paella de cuina':['cuinar','foc','mànec','fregir','paella'],
 'La Gioconda':['Mona Lisa','Leonardo','Da Vinci','somriure','Louvre'], 'La nit estrellada':['Van Gogh','cel','estrelles','xiprer','nit'], 'El crit':['Munch','angoixa','crit','Noruega','expressió'], 'Guernica':['Picasso','guerra','toro','cavall','bombardeig'], 'El petó':['Klimt','or','abraçada','parella','Viena'], 'La persistència de la memòria':['Dalí','rellotges','surrealisme','temps','tous'], 'Noia amb una arracada de perla':['Vermeer','perla','turbant','retratat','Delft'], 'El naixement de Venus':['Botticelli','petxina','deessa','Florència','mar']
};
const GAME_MODES=Object.fromEntries(Object.entries(RAW_MODES).map(([key,entries])=>[key,{label:MODE_INFO[key][0],icon:MODE_INFO[key][1],items:entries.map(entry=>{const [name,file]=entry.split('|'),details=CARD_DETAILS[name]||[];return{name,file,taboo:[name,...details],hints:[MODE_INFO[key][3]]}})}]));
const ROUND_SECONDS=120,RING_CIRCUMFERENCE=2*Math.PI*88;
let bag=[],current=null,activeMode='monuments',round=0,timeLeft=ROUND_SECONDS,timerInterval=null,running=false,hintsVisible=false,scores={t1:0,t2:0},audioCtx=null;
const $=id=>document.getElementById(id);
function refillBag(){bag=GAME_MODES[activeMode].items.map((_,i)=>i);for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}}
function renderChips(id,words){const el=$(id);el.innerHTML='';words.forEach(word=>{const chip=document.createElement('span');chip.className='chip';chip.textContent=word;el.appendChild(chip)})}
function nextRound(){if(!bag.length)refillBag();current=GAME_MODES[activeMode].items[bag.pop()];round++;hintsVisible=false;$('hintsPanel').classList.remove('visible');$('hintsBtn').textContent='💡 Mostrar pistes';$('roundTag').textContent=`${GAME_MODES[activeMode].label} · ronda ${round}`;$('monumentName').textContent=current.name;renderChips('tabooChips',current.taboo);renderChips('hintsChips',current.hints);$('tabooPanel').style.display='block';loadImage(current);stopTimer();timeLeft=ROUND_SECONDS;updateTimerDisplay()}
function changeMode(mode){activeMode=mode;bag=[];current=null;round=0;stopTimer();resetTimer();hintsVisible=false;$('roundTag').textContent=`${GAME_MODES[mode].label} seleccionada`;$('monumentName').textContent='';$('tabooPanel').style.display='none';$('hintsPanel').classList.remove('visible');$('hintsBtn').textContent='💡 Mostrar pistes';showStartPlaceholder()}
function showStartPlaceholder(){const frame=$('frame');frame.innerHTML=`<div class="placeholder"><div class="big-emoji">${GAME_MODES[activeMode].icon}</div><div>Prem «Nova ronda» per començar</div></div>`}
function loadImage(item){const frame=$('frame'),img=new Image(),path=`assets/${activeMode}/${item.file}`;frame.innerHTML='<div class="loader"></div>';img.onload=()=>{frame.innerHTML='';img.alt=item.name;frame.appendChild(img)};img.onerror=()=>{if(img.dataset.fallback)showPlaceholder(item,path);else{img.dataset.fallback='true';img.src=`assets/${activeMode}/fallback.svg`}};img.src=path}
function showPlaceholder(item,path){$('frame').innerHTML=`<div class="placeholder"><div class="big-emoji">${GAME_MODES[activeMode].icon}</div><div>No s'ha trobat la imatge local de <strong>${item.name}</strong>.</div><div class="eyebrow">${path}</div></div>`}
function toggleHints(){hintsVisible=!hintsVisible;$('hintsPanel').classList.toggle('visible',hintsVisible);$('hintsBtn').textContent=hintsVisible?'💡 Amagar pistes':'💡 Mostrar pistes'}
function updateTimerDisplay(){const m=Math.floor(timeLeft/60).toString().padStart(2,'0'),s=Math.floor(timeLeft%60).toString().padStart(2,'0'),num=$('timerNum'),ring=$('ringProgress');num.textContent=`${m}:${s}`;ring.style.strokeDasharray=RING_CIRCUMFERENCE;ring.style.strokeDashoffset=RING_CIRCUMFERENCE*(1-Math.max(0,timeLeft)/ROUND_SECONDS);num.classList.toggle('warn',timeLeft<=10&&timeLeft>0);ring.classList.toggle('warn',timeLeft<=10)}
function toggleTimer(){if(!current)nextRound();if(running)pauseTimer();else startTimer()}function startTimer(){if(timeLeft<=0)return;running=true;$('playBtn').textContent='⏸ Pausa';timerInterval=setInterval(()=>{timeLeft--;updateTimerDisplay();if(timeLeft<=0){stopTimer();triggerAlarm()}},1000)}function pauseTimer(){running=false;$('playBtn').textContent='▶ Iniciar';clearInterval(timerInterval)}function stopTimer(){pauseTimer()}function resetTimer(){stopTimer();timeLeft=ROUND_SECONDS;updateTimerDisplay()}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}function playAlarmSound(){try{ensureAudio();[880,880,880,660].forEach((freq,i)=>{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),start=i*.25;osc.type='square';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,audioCtx.currentTime+start);gain.gain.exponentialRampToValueAtTime(.35,audioCtx.currentTime+start+.02);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+start+.18);osc.connect(gain).connect(audioCtx.destination);osc.start(audioCtx.currentTime+start);osc.stop(audioCtx.currentTime+start+.23)})}catch{}}function triggerAlarm(){$('alarmOverlay').classList.add('active');playAlarmSound()}function closeAlarm(){$('alarmOverlay').classList.remove('active')}
function updateScore(team,delta){scores[team]=Math.max(0,scores[team]+delta);$(team==='t1'?'score1':'score2').textContent=scores[team]}function resetScores(){scores={t1:0,t2:0};$('score1').textContent=0;$('score2').textContent=0}function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen().catch(()=>{});else document.exitFullscreen().catch(()=>{})}
refillBag();updateTimerDisplay();document.querySelector('.dock').addEventListener('click',()=>{try{ensureAudio()}catch{}},{once:true});
